In [1]:
import numpy as np

## * Help function is useful to find all the data about any function

In [4]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

In [6]:
# np.array([array],dtype="")
a = np.array([1,2,3])
b = np.array([[1,2],[3,4]])
print(a)
print(b)

[1 2 3]
[[1 2]
 [3 4]]


* change into data type

In [7]:
c = np.array([1,2,3,4],"complex")
print(c)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


* arange function

In [8]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`. See the warnings section below for more information.
    
    Parameters
    ----------
    start : integer or real, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : integer or real
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off 

In [9]:
# np.arange(start,stop,step,dtype="") same as range() in python.
a = np.arange(1,10,1,dtype="float")
print(a)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [10]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
   

In [13]:
a = np.zeros((2,2),dtype="int")
b = np.zeros(6,"int")
print(a)
print(b)

[[0 0]
 [0 0]]
[0 0 0 0 0 0]


In [14]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. versionadded:: 1.20

In [17]:
a = np.ones(shape=(3,3),dtype="float")
b = np.ones(7,"int")
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[1 1 1 1 1 1 1]


In [19]:
help(np.empty)

Help on built-in function empty in module numpy:

empty(...)
    empty(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, without initializing entries.
    
    Parameters
    ----------
    shape : int or tuple of int
        Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        Desired output data-type for the array, e.g, `numpy.int8`. Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this 

In [26]:
# outputs the array with some random values.
a = np.empty(shape=(3,3),dtype="int")
b = np.empty(4,dtype="int")
print(a)
print(b)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[0 0 0 0]


In [27]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

In [31]:
# linspace returns evenly space values between start and stop of a particular count of numbers.
a = np.linspace(1,40,num=5)
print(a)
# The difference between every two values

b = np.linspace(1,10,num=3,endpoint = False,dtype='int')
# 10 is excluded .default num value is 50.
print(b)

[ 1.   10.75 20.5  30.25 40.  ]
[1 4 7]


In [32]:
help(np.eye)

Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_functi

In [34]:
# k parameter is the index of the main diagonal.
a = np.eye(3,3)
print(a)
b= np.eye(5,dtype="float",k=2)
print(b)
# if is positive then diagonal shift to up of main diagonal else negative then the diagonal shift to down of the diagonal.
c = np.eye(5,dtype="int",k=-1)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]]


In [35]:
help(np.identity)

Help on function identity in module numpy:

identity(n, dtype=None, *, like=None)
    Return the identity array.
    
    The identity array is a square array with ones on
    the main diagonal.
    
    Parameters
    ----------
    n : int
        Number of rows (and columns) in `n` x `n` output.
    dtype : data-type, optional
        Data-type of the output.  Defaults to ``float``.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. versionadded:: 1.20.0
    
    Returns
    -------
    out : ndarray
        `n` x `n` array with its main diagonal set to one,
        and all other elements 0.
    
    Examples
    --------
    >>> np.identity(3)
    array([[1.

In [37]:
# returns a identitiy matrix
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [40]:
# To know how many dimension ndim attribute.
a = np.array([1,2,3,4])
print(a.ndim)
b = np.array([[1,2],[3,4]])
print(b.ndim)

1
2


In [41]:
# shape of the array
print(a.shape)
print(b.shape)

(4,)
(2, 2)


In [42]:
# datatype of the array
print(a.dtype)
print(b.dtype)

int32
int32


In [43]:
# item size of an array returns no of elements present into the array.
print(a.itemsize)
print(b.itemsize)

4
4


In [45]:
# Indexing in the array.
# positive index starts from 0.Begining of the array.
# negative index of the array starts from -1 . From the end of the array

print(b[0][-1])

2


In [46]:
# slicing of the array
print(b[1][:2])

[3 4]


In [49]:
a = np.arange(5,dtype="int")
print(a)
print(a+2)
print(a-2)
print(a*2)
print(a/2)

[0 1 2 3 4]
[2 3 4 5 6]
[-2 -1  0  1  2]
[0 2 4 6 8]
[0.  0.5 1.  1.5 2. ]


In [50]:
b = np.array([[1,2],[3,4]],"int")
print(b)
print(b*2)

[[1 2]
 [3 4]]
[[2 4]
 [6 8]]


In [51]:
a = np.arange(1,5)
b = np.array([4,5,8,9])
print(a+b)
print(a*b)

[ 5  7 11 13]
[ 4 10 24 36]


* reshape

In [52]:
help(np.reshape)

Help on function reshape in module numpy:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
        c

In [53]:
# np.reshape(array,newshape=(),order={C,F})
# C is rowwise and F is columnwise.
a = np.arange(10)
b = np.reshape(a,newshape=(5,2))
print(b)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [58]:
c = np.reshape(a,newshape=(5,2),order="F")
print(c)
# first fill all the columns and then the rows.

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [56]:
help(np.resize)

Help on function resize in module numpy:

resize(a, new_shape)
    Return a new array with the specified shape.
    
    If the new array is larger than the original array, then the new
    array is filled with repeated copies of `a`.  Note that this behavior
    is different from a.resize(new_shape) which fills with zeros instead
    of repeated copies of `a`.
    
    Parameters
    ----------
    a : array_like
        Array to be resized.
    
    new_shape : int or tuple of int
        Shape of resized array.
    
    Returns
    -------
    reshaped_array : ndarray
        The new array is formed from the data in the old array, repeated
        if necessary to fill out the required number of elements.  The
        data are repeated iterating over the array in C-order.
    
    See Also
    --------
    numpy.reshape : Reshape an array without changing the total size.
    numpy.pad : Enlarge and pad an array.
    numpy.repeat : Repeat elements of an array.
    ndarray.resize : res

In [86]:
# np.resize(array,new_shape=())
# resize function places with repeated value of same array if the size is more than original array.In reshape it gives errors.
a = np.arange(5)
b = np.resize(a,new_shape=(5,3))
print(a)
print(b)
b[0][0]=4354
print(b)

[0 1 2 3 4]
[[0 1 2]
 [3 4 0]
 [1 2 3]
 [4 0 1]
 [2 3 4]]
[[4354    1    2]
 [   3    4    0]
 [   1    2    3]
 [   4    0    1]
 [   2    3    4]]
None


In [64]:
# resize function on an array will fill zeros if the size is greater than the value.
a.resize((2,5))
print(a)

[[0 1 2 3 4]
 [0 0 0 0 0]]


#### * flatten() returns a copy of the array collapsed into one dimension

In [87]:
a = np.array([[5,6],[7,8]])
print(a.flatten())

[5 6 7 8]
None


In [66]:
print(a.flatten(order = "F"))

[5 7 6 8]


In [67]:
b = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(b.flatten())

[1 2 3 4 5 6 7 8 9]


In [68]:
print(b.flatten(order="F"))

[1 4 7 2 5 8 3 6 9]


#### * ravel() returns a copy of array in one dimension array.

In [71]:
help(np.ravel)

Help on function ravel in module numpy:

ravel(a, order='C')
    Return a contiguous flattened array.
    
    A 1-D array, containing the elements of the input, is returned.  A copy is
    made only if needed.
    
    As of NumPy 1.10, the returned array will have the same type as the input
    array. (for example, a masked array will be returned for a masked array
    input)
    
    Parameters
    ----------
    a : array_like
        Input array.  The elements in `a` are read in the order specified by
        `order`, and packed as a 1-D array.
    order : {'C','F', 'A', 'K'}, optional
    
        The elements of `a` are read using this index order. 'C' means
        to index the elements in row-major, C-style order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest.  'F' means to index the elements
        in column-major, Fortran-style order, with the
        first index changing fastest, and the last index changing
       

In [73]:
# order ="F" is columnwise.
print(b)
print(np.ravel(b,order="F"))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[1 4 7 2 5 8 3 6 9]


#### * transpose() shifts us the elements along the axis

In [74]:
help(np.transpose)

Help on function transpose in module numpy:

transpose(a, axes=None)
    Reverse or permute the axes of an array; returns the modified array.
    
    For an array a with two axes, transpose(a) gives the matrix transpose.
    
    Refer to `numpy.ndarray.transpose` for full documentation.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axes : tuple or list of ints, optional
        If specified, it must be a tuple or list which contains a permutation of
        [0,1,..,N-1] where N is the number of axes of a.  The i'th axis of the
        returned array will correspond to the axis numbered ``axes[i]`` of the
        input.  If not specified, defaults to ``range(a.ndim)[::-1]``, which
        reverses the order of the axes.
    
    Returns
    -------
    p : ndarray
        `a` with its axes permuted.  A view is returned whenever
        possible.
    
    See Also
    --------
    ndarray.transpose : Equivalent method
    moveaxis
    argsort
    
    N

In [84]:
a = np.arange(1,11).reshape(5,2)
print(a)
print(a.shape)
b = a.transpose()
print(b)
print(b.shape)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
(5, 2)
[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]
(2, 5)
[ 1  2  3  4  5  6  7  8  9 10] [ 1  2  3  4  5  6  7  8  9 10]


In [83]:
help(np.swapaxes)

Help on function swapaxes in module numpy:

swapaxes(a, axis1, axis2)
    Interchange two axes of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axis1 : int
        First axis.
    axis2 : int
        Second axis.
    
    Returns
    -------
    a_swapped : ndarray
        For NumPy >= 1.10.0, if `a` is an ndarray, then a view of `a` is
        returned; otherwise a new array is created. For earlier NumPy
        versions a view of `a` is returned only if the order of the
        axes is changed, otherwise the input array is returned.
    
    Examples
    --------
    >>> x = np.array([[1,2,3]])
    >>> np.swapaxes(x,0,1)
    array([[1],
           [2],
           [3]])
    
    >>> x = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
    >>> x
    array([[[0, 1],
            [2, 3]],
           [[4, 5],
            [6, 7]]])
    
    >>> np.swapaxes(x,0,2)
    array([[[0, 4],
            [2, 6]],
           [[1, 5],
            [3, 7]]])



In [94]:
a = np.array([[1,2],[3,4]])
# print(a.base)# returns none if it owns the data else returns the array.
print(np.swapaxes(a,1,0))

[[1 3]
 [2 4]]


In [102]:
b = np.array([[1,2,3]])
print(np.swapaxes(b,0,1))

[[1]
 [2]
 [3]]


In [106]:
c = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
print(np.swapaxes(c,0,1))

[[[0 1]
  [4 5]]

 [[2 3]
  [6 7]]]


#### * concatenate()

In [110]:
# np.concatenate((a,b,c,*))
a = np.arange(1,5)
b = np.arange(4,9)
c = np.arange(5,10)
print(np.concatenate((a,b,c)))

[1 2 3 4 4 5 6 7 8 5 6 7 8 9]


In [111]:
a = np.array([1,2])
b = np.array([9,8])
print(np.concatenate((a,b)))

[1 2 9 8]


In [112]:
print(a+b)

[10 10]


In [113]:
print(a*b)

[ 9 16]


In [115]:
a = np.arange(1,5).reshape(2,2)
b = np.arange(5,9).reshape(2,2)
print(a)
print(b)
print(a*b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 5 12]
 [21 32]]


In [116]:
help(np.dot)

Help on function dot in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
      and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    Parameters
    ----------
    a : array_like
        First argument.
    b : array_like
        Second argument.
    out : 

In [117]:
print(np.dot(a,b))

[[19 22]
 [43 50]]


In [120]:
help(np.linalg.inv)

Help on function inv in module numpy.linalg:

inv(a)
    Compute the (multiplicative) inverse of a matrix.
    
    Given a square matrix `a`, return the matrix `ainv` satisfying
    ``dot(a, ainv) = dot(ainv, a) = eye(a.shape[0])``.
    
    Parameters
    ----------
    a : (..., M, M) array_like
        Matrix to be inverted.
    
    Returns
    -------
    ainv : (..., M, M) ndarray or matrix
        (Multiplicative) inverse of the matrix `a`.
    
    Raises
    ------
    LinAlgError
        If `a` is not square or inversion fails.
    
    See Also
    --------
    scipy.linalg.inv : Similar function in SciPy.
    
    Notes
    -----
    
    .. versionadded:: 1.8.0
    
    Broadcasting rules apply, see the `numpy.linalg` documentation for
    details.
    
    Examples
    --------
    >>> from numpy.linalg import inv
    >>> a = np.array([[1., 2.], [3., 4.]])
    >>> ainv = inv(a)
    >>> np.allclose(np.dot(a, ainv), np.eye(2))
    True
    >>> np.allclose(np.dot(ainv, a), 

In [124]:
a = np.arange(1,5).reshape(2,2)
print(np.linalg.inv(a)) # must pass 2d array.

[[-2.   1. ]
 [ 1.5 -0.5]]


In [125]:
# matrix power.
print(np.linalg.matrix_power(a,2))

[[ 7 10]
 [15 22]]


In [126]:
help(np.linalg.det)

Help on function det in module numpy.linalg:

det(a)
    Compute the determinant of an array.
    
    Parameters
    ----------
    a : (..., M, M) array_like
        Input array to compute determinants for.
    
    Returns
    -------
    det : (...) array_like
        Determinant of `a`.
    
    See Also
    --------
    slogdet : Another way to represent the determinant, more suitable
      for large matrices where underflow/overflow may occur.
    scipy.linalg.det : Similar function in SciPy.
    
    Notes
    -----
    
    .. versionadded:: 1.8.0
    
    Broadcasting rules apply, see the `numpy.linalg` documentation for
    details.
    
    The determinant is computed via LU factorization using the LAPACK
    routine ``z/dgetrf``.
    
    Examples
    --------
    The determinant of a 2-D array [[a, b], [c, d]] is ad - bc:
    
    >>> a = np.array([[1, 2], [3, 4]])
    >>> np.linalg.det(a)
    -2.0 # may vary
    
    Computing determinants for a stack of matrices:
    
 

In [127]:
print(np.linalg.det(a))

-2.0000000000000004


In [130]:
c = round(np.linalg.det(a))

In [131]:
print(c)

-2
